; voltmeter
    .org 8000h
    .equ adc, 0xFE20
    .equ portA, 0xFE30
    .equ portB, 0xFE31
    .equ portC, 0xFE32
    .equ control, 0xFE33
    ; port A is located at FE30h
    ; port B is unused
    ; port C is located at FE32h
    ; control reg is located at FE33h

;*************************************************
; set up the display
;*************************************************
setup:
    ; intialize stack at 40h
    mov SP, #40h

    ; set all ports to output
    mov DPTR, #control
    mov A, #80h
    movx @DPTR, A

    ; initialize 8-bit comm, 5x7 char set
    mov A, #38h
    lcall write_cmd

    ; turn display on, hide cursor
    mov A, #0Ch
    lcall write_cmd

    ; clear screen
    mov A, #01h
    lcall write_cmd

main:
    ; reset cursor without erasing 
    mov A, #02h         ; return home command
    lcall write_cmd

    ; write to the adc
    ; this triggers the snapshot
    mov DPTR, #adc
    mov A, #00h
    movx @DPTR, A 

    ; next read the adc
    movx A, @DPTR

    ; perform mult by 2500mV and store result in R3-R5 (LSB-MSB)
    lcall mult

    ; next divide by 256
    ; this is equivalent to shifting right by 8
    ; or just taking R4 to be the new LSB and discard R3
    ; the result is thus store in R5,R4
    ; we now need to convert this to decimal before we can send to LCD

    ; extract digits will store digits in 30h-35h
    lcall extract_digits

    ; send data to display
    ; add 30h for ascii
    ; also return home
    mov A, 30h
    add A, #30h
    lcall write_data

    mov A, #'.'
    lcall write_data

    mov A, 31h
    add A, #30h
    lcall write_data

    mov A, 32h
    add A, #30h
    lcall write_data

    mov A, 33h
    add A, #30h 
    lcall write_data

    mov A, #'V'
    lcall write_data

    sjmp main

;*************************************************
; extract digits from R5,R4 (MSB,LSB)
; digits will be stored in 30h-35h (MSB-LSB)
;*************************************************
extract_digits:
    mov 30h, #00h       ; Initialize Thousands counter
sub_1000:
    clr C
    mov A, R4
    subb A, #0E8h       ; 1000 is 03E8h. Subtract Low Byte (E8h)
    mov R4, A
    mov A, R5
    subb A, #03h        ; Subtract High Byte (03h)
    mov R5, A
    jc add_back_1000    ; If carry, we underflowed! Stop subtracting.
    inc 30h             ; Otherwise, count 1 thousand
    sjmp sub_1000
add_back_1000:
    mov A, R4           ; Restore the underflowed math
    add A, #0E8h
    mov R4, A
    mov A, R5
    addc A, #03h
    mov R5, A

    mov 31h, #00h
sub_100:
    clr C
    mov A, R4
    subb A, #64h        ; 100 is 0064h
    mov R4, A
    mov A, R5
    subb A, #00h
    mov R5, A
    jc add_back_100
    inc 31h
    sjmp sub_100
add_back_100:
    mov A, R4
    add A, #64h
    mov R4, A
    mov A, R5
    addc A, #00h
    mov R5, A

    ; Because the remainder is now < 100, it safely fits in 8 bits!
    ; We can finally use DIV AB for the last two digits.
    mov A, R4           ; The remaining value is strictly in the low byte now
    mov B, #0Ah         ; Divide by 10
    div AB
    mov 32h, A          ; Quotient is the Tens digit
    mov 33h, B          ; Remainder is the Ones digit

    ret

;*************************************************
; perform multiplication by 5000mV
;*************************************************
mult:
    mov R2, A       ; store adc result in R2

    ; perform low multiplication 
    mov A, #88h     ; load low byte of 2500d
    mov B, R2       ; load adc result
    mul AB          ; A = low byte of product, B = high byte of product
    
    mov R3, A       ; A goes straight to final LSB (R3)
    mov R4, B       ; B goes to middle byte accumulator (R4)

    ; perform high mult
    mov A, #13h     ; load high byte of 2500d
    mov B, R2       ; load adc result
    mul AB          
    
    ; add high mult to mid byte and MSB
    add A, R4       ; add new low byte to our existing middle byte
    mov R4, A       ; store the updated middle byte in R4
    
    mov A, B        ; move the new high byte into A
    addc A, #00h    ; add any carry generated by the middle byte addition
    mov R5, A       ; store the final MSB in R5

    ret

;*************************************************
; send hex in acc to LCD as instruction
;*************************************************
write_cmd:
    ; E is bit 2
    ; R/W is bit 1
    ; RS is bit 0
    ; RS = 0 for cmd
    
    ; push command from A to portA
    mov DPTR, #portA
    movx @DPTR, A 

    ; set E line is low and RS=0
    mov DPTR, #portC
    mov A, #00h
    movx @DPTR, A

    ; lift the E line
    mov DPTR, #portC
    mov A, #04h  
    movx @DPTR, A        

    ; lower the E line
    mov A, #00h
    movx @DPTR, A

    ; call delay subroutine to give 
    ; LCD display time

    lcall delay
    ret

;*************************************************
; send hex in acc to LCD as data
;*************************************************
write_data:
    ; E is bit 2
    ; R/W is bit 1
    ; RS is bit 0
    ; RS = 1 for data

    ; push data from A to portA
    mov DPTR, #portA
    movx @DPTR, A

    ; set E line low and RS=1
    mov DPTR, #portC
    mov A, #01h
    movx @DPTR, A

    ; lift the E line
    mov DPTR, #portC
    mov A, #05h
    movx @DPTR, A

    ; lower the E line
    mov A, #01h
    movx @DPTR, A 

    lcall delay
    ret

; we need a delay of at least 1.52 ms
; after the falling edge of the E line
delay:
    mov R7, #04h
outer:
    mov R6, #0FFh
inner:
    djnz R6, inner
    djnz R7, outer
    ret


